[build]
  publish = "apps"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "no-cache"

# Redirect جذر الموقع لداشبورد المؤسس
[[redirects]]
  from = "/"
  to = "/founder/index.html"
  status = 302
