services:
  - type: web
    name: qlevl-backend
    runtime: python
    rootDir: server
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000
      - key: DB_PATH
        value: qlevl.db
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
