-- ═══════════════════════════════════════════════════════
-- Migration 003: Guest sessions & tokens
--
-- §1 Rule #5: NEVER reuse guest tokens —
--             fresh per booking, expires at checkout.
--
-- Guests authenticate with token ONLY.
-- They NEVER appear in auth.users or public.users.
-- ═══════════════════════════════════════════════════════

CREATE TABLE public.guest_sessions (
    id                  UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    unit_id             UUID        NOT NULL
                                    REFERENCES public.units(id) ON DELETE CASCADE,

    -- Guest info (from iCal or manual entry)
    guest_name          TEXT,
    guest_phone         TEXT,
    party_size          INT         NOT NULL DEFAULT 1
                                    CHECK (party_size > 0),

    -- Booking window
    check_in            TIMESTAMPTZ NOT NULL,
    check_out           TIMESTAMPTZ NOT NULL,

    -- ─────────────────────────────────────────
    -- Token auth — the guest's ONLY credential
    -- Generated by Edge Function guest-token-create (§8)
    -- ─────────────────────────────────────────
    token               TEXT        UNIQUE NOT NULL,
    token_expires_at    TIMESTAMPTZ NOT NULL,

    -- Live session state (synced via Realtime — §7 Scenario 3)
    current_mode        TEXT        NOT NULL DEFAULT 'normal',

    -- Booking source
    source              TEXT        NOT NULL DEFAULT 'manual'
                                    CHECK (source IN (
                                        'manual', 'airbnb', 'booking', 'direct'
                                    )),
    ical_uid            TEXT,       -- de-duplication key from iCal

    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT chk_checkout_after_checkin CHECK (check_out > check_in)
);

CREATE TRIGGER trg_sessions_updated_at
    BEFORE UPDATE ON public.guest_sessions
    FOR EACH ROW EXECUTE FUNCTION public.update_updated_at();

COMMENT ON TABLE  public.guest_sessions             IS 'One row per booking. Token is the only credential. Expires at checkout.';
COMMENT ON COLUMN public.guest_sessions.token       IS 'Unique, non-reusable. Created by guest-token-create Edge Function.';
COMMENT ON COLUMN public.guest_sessions.current_mode IS 'Broadcast via Realtime to tablet + Pi on change (§7 Scenario 3).';
COMMENT ON COLUMN public.guest_sessions.ical_uid    IS 'iCal UID — prevents duplicate imports from multiple syncs.';
